name: Go MySQL Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up MySQL container
        run: make setup

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if docker exec mysql-test-container mysqladmin ping -h "localhost" -uroot -prootpass --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Go tests
        run: make test
